<?php

class SceneTableSeeder extends Seeder {

    public function run()
    {
      Scene::create([
        'chapter_id' => 5,
        'scene_order' => 1,
        'title' => 'Scene 1',
        'description' => '',
        'body' => '
          <p>Scene 1 of Chapter 4. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
        '
      ]);
      Scene::create([
        'chapter_id' => 1,
        'scene_order' => 2,
        'title' => 'Scene 2',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.',
        'body' => '
          <p>Scene 2 of Chapter 1. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
        '
      ]);
      Scene::create([
        'chapter_id' => 3,
        'scene_order' => 2,
        'title' => 'Scene 2',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.',
        'body' => '
          <p>Scene 2 of Chapter 2. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
        '
      ]);
      Scene::create([
        'chapter_id' => 1,
        'scene_order' => 1,
        'title' => 'Scene 1',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.',
        'body' => '
          <p>Scene 1 of Chapter 1. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
        '
      ]);
      Scene::create([
        'chapter_id' => 3,
        'scene_order' => 3,
        'title' => 'Scene 3',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.',
        'body' => '
          <p>Scene 3 of Chapter 2. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
        '
      ]);
      Scene::create([
        'chapter_id' => 3,
        'scene_order' => 1,
        'title' => 'Scene 1',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.',
        'body' => '
          <p>Scene 1 of Chapter 2. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
        '
      ]);
      Scene::create([
        'chapter_id' => 4,
        'scene_order' => 1,
        'title' => 'Scene 1',
        'description' => '',
        'body' => '
          <p>Scene 1 of Chapter 5. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo tempora magni quam ducimus dolor quae minima iusto minus pariatur molestias, eaque quasi, dolorum earum placeat eveniet dolore enim. Magni, hic! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum impedit maxime, sint illo ullam adipisci consequuntur temporibus voluptatibus possimus laudantium explicabo deserunt accusantium quae repellendus quasi ex debitis molestiae ea.</p>
        '
      ]);
    }

}